name: nsd_macos
description: Flutter network service discovery plugin (macOS submodule - will be installed with the parent plugin).
version: 2.0.1
repository: https://github.com/sebastianhaberey/nsd/tree/main/nsd_macos
issue_tracker: https://github.com/sebastianhaberey/nsd/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: NsdMacosPlugin
